name = "eparch"
version = "0.2.0"

description = "Gleam-friendly types for some poweful Erlang/OTP behaviours (like gen_statem and gen_event)"
licences = ["LGPL-3.0-or-later"]
repository = { type = "github", user = "schonfinkel", repo = "eparch" }
# links = [{ title = "Website", href = "" }]

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[documentation]
pages = [
    { title = "Examples", path = "examples/readme.html", source = "./examples/README.md" },
    { title = "Quick Start", path = "docs/quick_start.html", source = "./docs/Quick_Start.md" },
    { title = " ", path = "#", source = "" },
]
