name = "pushbutton"
version = "1.0.0"

description = "Pushbutton example for eparch/state_machine"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
eparch = { path = "../../" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
