# Generated by rebar3_nix
let
  fetchOnly = { src, ... }: src;
in
{
  builder ? fetchOnly,
  fetchHex,
  fetchgit,
  fetchFromGitHub,
  overrides ? (x: y: { }),
}:
let
  self = packages // (overrides self packages);
  packages = with self; {
  };
in
self
