name: "[Nix] Build & Test"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: "[Lib] Check, Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # To leverage devenv inside Github Actions
      - uses: cachix/cachix-action@v17
        with:
          name: devenv

      - name: "[Nix] Run treefmt to check Erlang / Gleam / Nix"
        run: |
          nix flake check

      - name: "[Nix] Build"
        run: |
          nix build

      - name: "[Gleam] Run Testing Suite"
        run: |
          nix develop --impure --command gleam test

      - name: "[Gleam] Check if all examples still work"
        run: |
          nix develop --impure --command make
